apiVersion: apps/v1
kind: Deployment
metadata:
  name: system2024-deployment
  namespace: system2024
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: kappsegla/system2024:sha-78e30b0
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 7999
            periodSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 7999
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: DB_LOCAL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: github_client_id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: github_client_secret
