name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "frontend/**"
      - "src/main/resources/static/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "frontend/**"
      - "src/main/resources/static/**"
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: maven
      - name: Compile with Maven
        run: mvn -B compile --file pom.xml

      - name: Test with Maven
        run: mvn -B test --file pom.xml
